#!/bin/bash
#PBS -N "tutorial-1-campus-cluster"
#PBS -W group_list=tallis
#PBS -q secondary
#PBS -l nodes=1:ppn=12
#PBS -l walltime="01:00:00"
#PBS -j oe
#PBS -M binghui2@illinois.edu
#PBS -m be

#="/projects/tallis/binghui2/reu2019-tutorials/1-campus-cluster/binghui2"
cd $PBS_O_WORKDIR
workdir=/projects/tallis/binghui2/reu2019-tutorials/1-campus-cluster/binghui2 
for i in {1..3}
do
	for j in {0..4}
	do
		inputToSeq="$workdir/../../data/100M$i/R$j/rose.aln.true.fasta"
		SeqOutput="$workdir/../../data/100M$i/R$j/rose.aln.true.phy"
		python3 $workdir/seqtools.py -f p -i $inputToSeq -o $SeqOutput
		#eval $command0
		resfile1="$workdir/res/NJ+LogDetM$i$j"
		fastme-2.1.5-linux64-omp -i $SeqOutput -o $resfile1 -m N -d L -T 12
		#eval $command1
		resfile2="$workdir/res/BIONJ+LogDetM$i$j"
		fastme-2.1.5-linux64-omp -i $SeqOutput -o $resfile2 -m I -d L -T 12
		#eval $command2
		resfile3="$workdir/res/NJ+p-distanceM$i$j"
		fastme-2.1.5-linux64-omp -i $SeqOutput -o $resfile3 -m N -d p -T 12
		#eval $command3
		resfile4="$workdir/res/BIONJ+p-distanceM$i$j"
		fastme-2.1.5-linux64-omp -i $SeqOutput -o $resfile4 -m I -d p -T 12
		#eval $command4
	done
done
