#!/bin/bash
#PBS -N "tutorial-1-campus-cluster"
#PBS -W group_list=tallis
#PBS -q secondary
#PBS -l nodes=1:ppn=12
#PBS -l walltime="01:00:00"
#PBS -j oe
#PBS -M binghui2@illinois.edu
#PBS -m be

PBS_O_WORKDIR="/projects/tallis/binghui2/reu2019-tutorials/1-campus-cluster/binghui2"
cd $PBS_O_WORKDIR
for i in {1..3}
do
	for j in {0..4}
	do
		python3 seqtools.py -f p -i ../../data/100M$i/R$j/rose.aln.true.fasta -o ../../data/100M$i/R$j/rose.aln.true.phy
		#eval $command0
		resfile1="../../data/NJ+LogDetM$i$j"
		fastme-2.1.5-linux64-omp -i ../../data/100M$i/R$j/rose.aln.true.phy -o $resfile1 -m N -d L
		#eval $command1
		resfile2="../../data/BIONJ+LogDetM$i$j"
		fastme-2.1.5-linux64-omp -i ../../data/100M$i/R$j/rose.aln.true.phy -o $resfile2 -m I -d L
		#eval $command2
		resfile3="../../data/NJ+p-distanceM$i$j"
		fastme-2.1.5-linux64-omp -i ../../data/100M$i/R$j/rose.aln.true.phy -o $resfile3 -m N -d p
		#eval $command3
		resfile4="../../data/BIONJ+p-distanceM$i$j"
		fastme-2.1.5-linux64-omp -i ../../data/100M$i/R$j/rose.aln.true.phy -o $resfile4 -m I -d p
		#eval $command4
	done
done
