#!/bin/bash
#PBS -N "tutorial-1-campus-cluster"
#PBS -W group_list=tallis
#PBS -q secondary
#PBS -l nodes=1:ppn=12
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -M ebhamel2@illinois.edu
#PBS -m be
#PBS -o tutorial-1-campus-cluster.out
#PBS -e tutorial-1-campus-cluster.err

seqtools=/projects/tallis/hamel/reu2019-tutorials/tools/seqtools.py

#check if seqtools.py exists and can be executed
if [ ! -x $seqtools ];
then
        echo "Seqtools file could not be found or run"
	exit 1
fi

output=/projects/tallis/hamel/reu2019-tutorials/1-campus-cluster/ebhamel2/results
cd $output

#loop through all the M's
for modl in 100M1 100M2 100M3
do
	#loop though all the reps
	for rep in R0 R1 R2 R3 R4
	do
		path=/projects/tallis/hamel/reu2019-tutorials/data/$modl/$rep
		
		#check if the true fasta is there
		if [ ! -e $path/rose.aln.true.fasta ];
		then
    			echo "Could not find file " + $path/rose.aln.true.fasta
			exit 1
		fi
		
		#convert files to .phy	
		python3 $seqtools -f p -i $path/rose.aln.true.fasta -o $path/rose.aln.true.phy
		fastme-2.1.5-linux64-omp \
    			-i $path/rose.aln.true.phy \
    			-o $output/NJ_on_p_dist_${modl}_${rep}.tre \
    			-m N --dna=p-distance \
			-T 12

		fastme-2.1.5-linux64-omp \
                        -i $path/rose.aln.true.phy \
                        -o $output/NJ_on_Log_Det_${modl}_${rep}.tre \
                        -m N --dna=LogDet \
                        -T 12 

		fastme-2.1.5-linux64-omp \
                        -i $path/rose.aln.true.phy \
                        -o $output/BioNJ_on_p_dist_${modl}_${rep}.tre \
                        -m I --dna=p-distance \
                        -T 12

		fastme-2.1.5-linux64-omp \
                        -i $path/rose.aln.true.phy \
                        -o $output/BioNJ_on_Log_Det_${modl}_${rep}.tre \
                        -m I --dna=LogDet \
                        -T 12
	done
done
