#!/bin/bash
#PBS -N "tutorial-1-campus-cluster"
#PBS -W group_list=tallis
#PBS -q secondary
#PBS -l nodes=1:ppn=12
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -M ebhamel2@illinois.edu
#PBS -m be
#PBS -o a_run_indelible_scaled.out
#PBS -e a_run_indelible_scaled.err

control=/projects/tallis/reu2019/software/INDELibleV1.03/src/control.txt
mm=/projects/tallis/hamel/reu2019-tutorials/4-all/ebhamel2/modeltree_modifier.py
st=/projects/tallis/hamel/reu2019-tutorials/4-all/ebhamel2/scaled_tree/modeltrees

cd /projects/tallis/reu2019/software/INDELibleV1.03/src/

for rep in R0 R1 R2 R3 R4
do
	#python3 $mm /projects/tallis/hamel/reu2019-tutorials/4-all/data/100M3/$rep/rose.mt
		for entry in $st/*$rep*
		do 
			> $control
			line=$(head -n 1 $entry)
			scale=$(echo $entry | sed 's/.*scale_\(.*\)\.tre/\1/')
			output_file=/projects/tallis/hamel/reu2019-tutorials/4-all/ebhamel2/scaled_tree/alignment_${rep}_${scale}
			printf "[TYPE] NUCLEOTIDE 1\n" >> $control
			printf "[MODEL] modelname\n" >> $control
			printf "[submodel] GTR 0.318706 0.083336 0.126271 0.450343 0.089108\n" >> $control
			printf "[TREE] treename $line\n" >> $control
			printf "[PARTITIONS] partitionname\n" >> $control
			printf "[treename modelname 1000]\n" >> $control
			printf "[EVOLVE] partitionname 1 $output_file\n" >> $control
			/projects/tallis/reu2019/software/INDELibleV1.03/src/indelible $control
	done
done
