#!/bin/bash
#PBS -N "tutorial-1-campus-cluster"
#PBS -W group_list=tallis
#PBS -q secondary
#PBS -l nodes=1:ppn=12
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -M nikhila4@illinois.edu
#PBS -m be

#cd $PBS_O_WORKDIR

for i in {1..3}
	do
		for j in {0..4}
			do
				#Format conversionm
				in="/projects/tallis/nikhila4/reu2019-tutorials/data/100M$i/R$j/rose.aln.true.fasta"
				out="/projects/tallis/nikhila4/reu2019-tutorials/data/100M$i/R$j/rose.aln.true.phy"
				python /projects/tallis/nikhila4/reu2019-tutorials/tools/seqtools.py -f p -i $in -o $out

				#Runing fastME
				out2="/projects/tallis/nikhila4/reu2019-tutorials/1-campus-cluster/nikhila4/results/NJ_LogDet_100M${i}_R$j"
				fastme-2.1.5-linux64-omp -i $out -o $out2 -m N -d L
				out2="/projects/tallis/nikhila4/reu2019-tutorials/1-campus-cluster/nikhila4/results/BioNJ_LogDet_100M${i}_R$j"
				fastme-2.1.5-linux64-omp -i $out -o $out2 -m I -d L
				out2="/projects/tallis/nikhila4/reu2019-tutorials/1-campus-cluster/nikhila4/results/NJ_P-Dist_100M${i}_R$j"
				fastme-2.1.5-linux64-omp -i $out -o $out2 -m N -d p
				out2="/projects/tallis/nikhila4/reu2019-tutorials/1-campus-cluster/nikhila4/results/BioNJ_P-Dist_100M${i}_R$j"
				fastme-2.1.5-linux64-omp -i $out -o $out2 -m I -d p

			done
	done

